fix: remove empty required array from json schema
In some versions of json schema an exception is raised.
jsonschema.exceptions.SchemaError: [] is too short